package verbs;
import core.Verb;
/**
 *
 * @author pedro
 */
public class Curse extends Verb {
    
    public Curse() {
        super("damn",
                new String[] {"anal",
                                "anus",
                                "arse",
                                "ass",
                                "ballsack",
                                "balls",
                                "bastard",
                                "bitch",
                                "blowjob",
                                "blow job",
                                "boner",
                                "boob",
                                "bum",
                                "butt",
                                "buttplug",
                                "clitoris",
                                "cock",
                                "cocksucker",
                                "coon",
                                "crap",
                                "cunt",
                                "dick",
                                "dildo",
                                "dyke",
                                "fag",
                                "fellate",
                                "fellatio",
                                "feltcher",
                                "fuck",
                                "f u c k",
                                "fudgepacker",
                                "fudge packer",
                                "goddamn",
                                "god damn",
                                "hell",
                                "homo",
                                "jizz",
                                "labia",
                                "motherfucker", 
                                "muff",
                                "nigger",
                                "nigga",
                                "penis",
                                "piss",
                                "poop",
                                "prick",
                                "pube",
                                "pussy",
                                "queef",
                                "queer",
                                "scrotum",
                                "sex",
                                "shit",
                                "slut",
                                "smegma",
                                "spunk",
                                "tit",
                                "tosser",
                                "twat",
                                "vagina",
                                "wank",
                                "whore"},
                new boolean[] {true, true, false});
    }
}
